// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6ARVwXQBYF5HibwlTt0DAumF6IOImIU',
    appId: '1:208548965320:web:8d0aa6affc3a866cb8eefd',
    messagingSenderId: '208548965320',
    projectId: 'edu-kid',
    authDomain: 'edu-kid.firebaseapp.com',
    databaseURL: 'https://edu-kid-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'edu-kid.appspot.com',
    measurementId: 'G-LYSNJRKD2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmAC8xeNvckOIZdssL5VWiJ-MUFsd6Bo',
    appId: '1:208548965320:android:9ca7abd77a1a451cb8eefd',
    messagingSenderId: '208548965320',
    projectId: 'edu-kid',
    databaseURL: 'https://edu-kid-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'edu-kid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6cjMh7hHIWhwIWxfC7DaYAQQFlvSnvO4',
    appId: '1:208548965320:ios:94f2e67585a0b15bb8eefd',
    messagingSenderId: '208548965320',
    projectId: 'edu-kid',
    databaseURL: 'https://edu-kid-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'edu-kid.appspot.com',
    iosClientId: '208548965320-4haje541kle8v6usctkfhlgtqj6jsd3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.edukid',
  );
}
